---
baseurl: ''
url: https://wamta-workshop.github.io
css: "./assets/hotweb.css"
current_year: '2027'
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- README.md
timezone: America/Eastern
google_analytics:
